export const majorList = [
    "Giáo dục Tiểu học",
    "Giáo dục Công dân",
    "Giáo dục Thể chất",
    "Sư phạm Toán học",
    "Sư phạm Tin học",
    "Giáo dục Vật lý",
    "Giáo dục Hóa học",
    "Sư phạm Sinh học",
    "Sư phạm Ngữ văn",
    "Giáo dục Lịch sử",
    "Giáo dục Địa lý",
    "Sư phạm Tiếng Anh",
    "Sư phạm Tiếng Pháp",
    "Công nghệ kỹ thuật hóa học",
    "Kỹ thuật vật liệu",
    "Quản lý công nghiệp",
    "Logistics và Quản lý chuỗi cung ứng",
    "Kỹ thuật cơ điện tử",
    "Kỹ thuật điều khiển và tự động hóa",
    "Kỹ thuật điện tử - viễn thông",
    "Kỹ thuật điện",
    "Kỹ thuật cấp thoát nước",
    "Kỹ thuật xây dựng",
    "Kỹ thuật xây dựng công trình thủy",
    "Kỹ thuật xây dựng công trình giao thông",
    "Truyền thông đa phương tiện",
    "An toàn thông tin",
    "Khoa học máy tính",
    "Kỹ thuật máy tính",
    "Mạng máy tính và truyền thông dữ liệu",
    "Kỹ thuật phần mềm",
    "Hệ thống thông tin",
    "Công nghệ thông tin",
    "Kế toán",
    "Kiểm toán",
    "Tài chính-Ngân hàng",
    "Quản trị kinh doanh",
    "Quản trị dịch vụ du lịch và lữ hành",
    "Marketing",
    "Kinh doanh thương mại",
    "Kinh doanh quốc tế",
    "Kinh tế",
    "Kinh tế nông nghiệp",
    "Luật"
]

export const courseList = ["44", "45", "46", "47", "48", "49", "50"];

export const capacity = ["2", "3", "4", "5", "6", "7", "8"];